# This job runs the project tests

name: Build and test

# Trigger the workflow on push or pull request to master or develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run tests on MASTER branch
        if: ${{ github.base_ref == 'master' }}
        env: 
          FBN_TOKEN_URL: ${{ secrets.DEVELOP_FBN_TOKEN_URL }}
          FBN_USERNAME: ${{ secrets.DEVELOP_FBN_USERNAME }}
          FBN_PASSWORD: ${{ secrets.DEVELOP_FBN_PASSWORD }}
          FBN_CLIENT_ID: ${{ secrets.DEVELOP_FBN_CLIENT_ID }}
          FBN_CLIENT_SECRET: ${{ secrets.DEVELOP_FBN_CLIENT_SECRET }}
          FBN_LUSID_API_URL: ${{ secrets.DEVELOP_FBN_LUSID_API_URL }}
          FBN_LUMI_API_URL: ${{ secrets.DEVELOP_FBN_LUMI_API_URL }}
          FBN_APP_NAME: ${{ secrets.DEVELOP_FBN_CLIENT_ID }}
          FBN_LUSID_ACCESS_TOKEN: ${{ secrets.DEVELOP_FBN_ACCESS_TOKEN }}
          FBN_DRIVE_API_URL: ${{ secrets.DEVELOP_FBN_DRIVE_API_URL }}
        run: |

          docker build -t luminesce-examples .
          docker run \
            -e FBN_TOKEN_URL=${FBN_TOKEN_URL} \
            -e FBN_USERNAME=${FBN_USERNAME} \
            -e FBN_PASSWORD=${FBN_PASSWORD} \
            -e FBN_CLIENT_ID=${FBN_CLIENT_ID} \
            -e FBN_CLIENT_SECRET=${FBN_CLIENT_SECRET} \
            -e FBN_LUSID_API_URL=${FBN_LUSID_API_URL} \
            -e FBN_LUMI_API_URL=${FBN_LUMI_API_URL} \
            -e FBN_APP_NAME=${FBN_APP_NAME} \
            -e FBN_LUSID_ACCESS_TOKEN=${FBN_LUSID_ACCESS_TOKEN} \
            -e FBN_DRIVE_API_URL=${FBN_DRIVE_API_URL} \
            luminesce-examples
